##colours
FG="#E8DDCF"
BG="#1A120D"
RED="#C9664f"
DARK_RED="#8A3B2A"
GREEN="#A4B95F"
YELLOW="#DEA23B"
BLUE="#7992A0"
MAGENTA="#B37265"
CYAN="#6DAB9F"
BLACK="#1A120D"
GRAY="#4B3A30"
DARK_GRAY="#3B2E26"
LIGHT_GRAY="#96816E"
