# Earth (My colour scheme)

background #1b130e
foreground #e8ddcf
cursor #cfc0af

selection_foreground #e8ddcf
selection_background #4b3a30

color0 #1b130e
color8  #96816e

color1  #893b2a
color9  #c9664f

color2  #5c6a2f
color10  #a4b95f

color3  #996a1a
color11  #dea23b

color4  #4a5e68
color12  #7992a0

color5  #7b473b
color13  #b37265

color6  #3d6b62
color14  #6dab9f

color7  #6b5747
color15  #e8ddcf

#	bg_h = "#1b130e", -- color0 black
#	bg0 = "#211812",
#	bg1 = "#291f19",
#	bg2 = "#3b2e26",
#	bg3 = "#4b3a30",
#	bg4 = "#6b5747",     -- color7 white
#
#	background = "#1b130e", -- color0 black
#
#	fg0 = "#96816e",     -- color8 bright_black
#	fg1 = "#b4a18d",
#	fg2 = "#c1b19f",
#	fg3 = "#cfc0af",
#	fg4 = "#dacdbe",
#	fg5 = "#e8ddcf",     -- color15 bright_white
#
#	foreground = "#e8ddcf", --color15 bright_white

# dark gray
# light gray
#
